[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "932f282690a789f3744abcd83fb9f68ba7ed4c19"
os = "macos"

    [[Libtiff.download]]
    sha256 = "f03ae6119679f0a1307fba80875ea9cabd74faad5fbee87d46aa34b6a2ad9290"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.aarch64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "3bd27d3a82c0e0055e79e335875863563002ea26"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "ff04bd824613f8b499fb25cd8b80627c798ec1da4843eead45850fa1db3e5120"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "37063ca1d7b77ceac6169330065c877fb4813723"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "849b030d154b71834935eb07ff3dead64dc029f78a3fba4fadfd6dbe220ac687"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "7c9dc1d46a18edc7b0f00c00aa9f304c6c16be9a"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "1fdbbd439515931c48228938d2354d720dbb966151a049dec97bfc73d2ef15b7"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.aarch64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6a6c1f46d0ecab0e33e81d5e56c0988e7b0812f"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "2e87e04171aac90d64bb8e718f83141c3f6bd10ff197fd09710c940463ca8092"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.armv6l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e837cb3c9bd2ad98934b83d5e795fda65652d0f"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "43a7600a64c93754b4bb7ba0d1f8de9c6b5a8cf4aa75095cd39487f9060d309b"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.armv6l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b69d75175ba015c217b463a5479d38f3c72b6099"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "922779b2d7fb396a9b7157b89d3b44f971116c183f79d59d9e8386c0f761773b"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.armv7l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "510efa268d4a7cff6b36f27d9d8989ee3d19768c"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d1b54931421b71b964179da8aa6b13f022b001dd305de0c6d5116f88b2e4817a"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.armv7l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "d1ed2b6643d290281f42d0f4187d91341c7d5011"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "3c015c21da5cd69174059bc9a42af06660552f1ad43e98f0f7d33be6fcf29609"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.i686-linux-gnu.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "85b1ebe7c92144bdee7cb277a0159c2b197032a9"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "c2ead73dcba73e6f5b4bc47c164a97fe4ca2b4da0ef10682156db059c84063fa"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "7dce8acde448021320cb22042b69cd5ea6287766"
os = "windows"

    [[Libtiff.download]]
    sha256 = "561a183d24a419c6b48934299a1f7a89d2443b2841fe20598e2f69d8d9add79a"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "e00c918523e1ddca2f3b23aaac9edb4ffa949206"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "1bf0d840d504a17e869983d42154046f0783416c0fd09587823edc3f535fe3ca"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "riscv64"
git-tree-sha1 = "b4edf516cf220aa9b7e159f8530244fefc553abf"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "3a857b79b3fb24e7ee4b089086eb18b34107efe0a3bd5f7dfdb3fbe615464a8f"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.riscv64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "b9ec538b4fff7e5af7966d095e1bd816e45beb64"
os = "macos"

    [[Libtiff.download]]
    sha256 = "e2513dc370df51e61bda7aef3776667fea5a40d16710a235a73afbf5ab141e86"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.x86_64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "21ed7b5e888fb9b18f44ba3f4652f14d8beda78c"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "8a9ab35a8caf9baf657e66b1afecf6ea18fb508d680eebd084cbedd627dd1282"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "2845028d7b2ff32920d7c656d9da60a28cc2d946"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "f6e9bcc43136df2b071eb02f215bef1970f199d56f060ac1402692570d440da8"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.x86_64-linux-musl.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "2d76fec8ff50bd7cf7bd7a72dafc1a81500127d9"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "eec589a5645a2c7c6850999f428874b1fdad6790911345b90ea39fa6d5bc6c25"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.x86_64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "5fefe63265b5e518250aa25b1fae792d179c0e97"
os = "windows"

    [[Libtiff.download]]
    sha256 = "c928bdeae6a2d9f9e9a13cad41651dee7c81b13e69cc222f7218ce5bc4da1390"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.1+0/Libtiff.v4.7.1.x86_64-w64-mingw32.tar.gz"
