[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "7e9ccc887a81ff5c25b426845a46a5b64ddbb364"
os = "macos"

    [[Libtiff.download]]
    sha256 = "d3668c1f4f5c9db9d9d25fcfb441afa62cee280397b62283e81ad4b6275c8911"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.aarch64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "e65c17c5c154aa89dbfcf11f99fe3fbbb2d649c8"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "8586127e9560c00e76135b0bbf0fbb82f0cf8531f1eef4eac42f071367819e17"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "8372639c992a19daa030f5899f267cd4b7196bad"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d0ad254414aba5bfb6469f74451e941d8657cab54aeba16cc35a32e002ad4657"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3234e9007830dfa3928bf33de4878379de6578cf"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "3b9dbd5f54660de0665910950135d6881a544103c60618fd980410023cec6c0b"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.armv6l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3934953198ac837fc74c97c1f3f701ad6680719"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "6b8e159603661979f2844c0eb70ee5eb847bdbaac11b85b19128a58e2015d8a3"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.armv6l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34867f9da15fcfa653152180fca01012dee9877d"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "f66fd8f720cf5a9ab4a5a403b5e94ff27953a0b3a09d5aac067b2bc76001678e"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c31a9e615d275fa0b4124dc261649388edf452e4"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d2f73c8c018a74e0fcf5f60029a1788ba0db1f88e554df031812a9405d4f84b5"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.armv7l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "164938caea64a5e0b6e08d62214ca9166512f5e5"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "6918c0ec29d295bf9293dc79ba20e3c65a968c08ea460ebdad92cd74083e41ca"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.i686-linux-gnu.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "52a00a995b2a3394a33070c2ca3bfe5a2199019d"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "77917367d421aaf01d25bc7683ed400304cb09d5672e1336b84a8643337d810a"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "a3b58a68a366e3e31aa67df36ffefbceb27a7792"
os = "windows"

    [[Libtiff.download]]
    sha256 = "445e914a567063cac70269741190fb25203425b5fd9c7854dbccf9e1226dd9de"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "17f90b9f3acb1410f09e41c297f816be7cc0764f"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "1c77548cea9b771539a4a36e12c405b7a7b9ecca305478f559ea8b32e2acae93"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "6cfd7aa13ff14fcbc9c65aa9b4b05b6763e19eeb"
os = "macos"

    [[Libtiff.download]]
    sha256 = "8213c4a63f312869655c60fec6eb5813c42cd59468d5a03ad2f148eef34642d1"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.x86_64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "10fab78219f14affc5f8905a26eaf75c118fe80a"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "54982811c695517308c9b5f878361b1abc8d7d3a6ed1094836b8d9f3aab80a09"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "0d52c1ba226f278398b3698de92981b31cf44d95"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "081ad782c060160e892c16b06ac4e398eb35ba20445eb6777e2821667d86cc49"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.x86_64-linux-musl.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "bd33ed5a5034d0523b23ed145cf3b114c54378e1"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "9e94ad0264ce9c90c131a2f5f5ea508d5f20875f295c8ef15ed937946cc4da9c"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.x86_64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "5ad3ddad38954ebc2f69d8c29048016ea37cac35"
os = "windows"

    [[Libtiff.download]]
    sha256 = "e3dfe254054b2820a78714c167bcf27d7efb9b55890f433d3061eb5dd21d2614"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.3.0+0/Libtiff.v4.3.0.x86_64-w64-mingw32.tar.gz"
