[[Libtiff]]
arch = "i686"
git-tree-sha1 = "f0546d5603f6d78c6f5e1d65c6c352f70f549cfb"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "74eaab3d302280ecfde4ff4781fea9e57c88adc88d6042fa6247a5c92d63874f"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "6f80de9a896ff4f37883268bb33deb44c263e28f"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "3711d7f3384c4628932a1b03a1f974532845a384dd5e889ab9de589858ccc145"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "546bb842555435c47199872e0f978647170238dc"
os = "windows"

    [[Libtiff.download]]
    sha256 = "9f8e15c051f1c6e213d6fa2fd84406d60049119cc827cc94b86053d1adf94a9a"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "f98adb5b4de5c29a8d77def412b792beaec6180b"
os = "windows"

    [[Libtiff.download]]
    sha256 = "e2692adb55ace1674b002c3a585f8887f689188eae0c2b358cd8ab0bf0e823e9"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.x86_64-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "armv7l"
git-tree-sha1 = "b1d542e3a8139526c0dd964a29967516484d750d"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "33967c33c7b28f91da302dc1e8a4b3e441e324c2acdb67fa8551d1c7609faeb6"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.armv7l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
git-tree-sha1 = "e26ccc7af563bdead465917389fddcbf151e12f6"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "fdfae3cad8f603a2cd20b86473341d50002dba2de26d01eb32fb29bdccc4078d"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.armv7l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "a386cb4c2690ac32a9d810314883fd915462dabe"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "5427bde66a020458c92db7d17db2da9d09ce4092ddd528e400b4f3ce6f133154"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.i686-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "6eaff1edf410716108e0d7304e525a3a5178cca7"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "1dc5a0eb61942229b81c8db1a8804dd88a17b639b80bdd07e3bd5ae79102e3ac"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "97e63bc9d71d67521cf7cb994c7a37ef21ce496f"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "45ab6d5151dccdb8b6ea4841f3004db87420a13ca0d8b32172e2fbe9f2521044"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "fc9ca9e78826c5a8d8a25369868aea0111d75824"
os = "macos"

    [[Libtiff.download]]
    sha256 = "433662a3c6241331ce63fc76ca06d20d3567f7cf28ab9ca6fb98e1fa9a19eb42"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.x86_64-apple-darwin14.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "68a25ec0da4b21dbae03eccec7316242b7a84676"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "77fe75ed5489527cb6fc2851b001c8063e34750f41a1762ffb91e91c1e36cde7"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "4656283fd26fcb594f169b310814da20061eaebe"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "b7d46b5c88a8865d577ca4a5e51dbe788f23a4dffc27cbb74e3071062eca7ded"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.x86_64-unknown-freebsd11.1.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "ad5475799da1300f47c0a01a29181c4bac35cf7e"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "60aef1654ecc2de4a6ad17beb98b1dd2ced6903f3e773a64d20579ffa572bfdb"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+1/Libtiff.v4.0.10.x86_64-linux-musl.tar.gz"
