[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "ee6e372e9d072ac88f1fa90e47112eccf9f6c915"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "4840f95acdc4cad729a50109824161e3bb5b1f8d91bf684b30da30c7eb50e8f2"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "4e89cb04a1fb00da4c52d74d05a7ac84f03b420d"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "558e2d67fbf6fbee9c0c34093bb89792233bcc734e867479d6d9b27876c64050"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "armv7l"
git-tree-sha1 = "6086be112c1ffd85c93c0303386dae77670a6075"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "9e836c5cacdc6740486def0ae9182513a3c42ba6166f2bab406a808cb9bb754c"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.arm-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
git-tree-sha1 = "79c1953d641986c5bb2c9af857ec83392405b56c"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "5e3e61eb72cfda2985a95d76649fb53d95e343adb666ece3cd55d60a38037ef2"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.arm-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "3a9a32da6cdebc7b9a9eabc476de18d204d6714e"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "5525988ea07d9a81560c4b40f6f25f573a86a480493178dee64df91907a873b3"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.x86_64-unknown-freebsd11.1.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "5a712ebd24da6d995816b192eb22a70bb3b8b00d"
os = "macos"

    [[Libtiff.download]]
    sha256 = "80da4e3aefea4df17ad32e463057f04acb417093addd3e0e3bc0f8517aa600e1"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.x86_64-apple-darwin14.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "7960b2bddd053b8222585190a7eb253453f6eeb4"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "848b40f0b56906718851d83e882e30b65f6c569f16e3dcbc0a61840e20ae81b2"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "4a3508f70aeb6b2c330573e03c3a30397fe5a893"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "c3322ec57708d6464396e3de2448baaea9f97a62453767b3056e49be3c76b4d4"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "923977d367181746ec9baa8a68eda68a08242674"
os = "windows"

    [[Libtiff.download]]
    sha256 = "c9b39e0427fdf6a0141e44e83d65ffb2b5d8879ab6379263db999b0e95ebf7d7"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "511f000f22596293bda9033a1f69c1527834682c"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "e9705da70aff2873147050dad7aa752e99900b0ec68e541ac98d845d27690946"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "a42da7330f9e38cf60d965fbb89277212c2ee423"
os = "windows"

    [[Libtiff.download]]
    sha256 = "0d00e870b948c24e90228a786280055bcab6e4bdee6b395ab0e0468c334406ce"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.x86_64-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "5a3e65a27a989e074d28d519278a54e7914de444"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "b464bcad446c58fa69675637e0c3b252ba51446174578e522c004780b74d3040"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.x86_64-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "55e0a7a54ed016b696e373a0cb671c84092b5d2d"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "7c71d49cde160e5454cb540fae40116b0916b4fccbf0a5dc15fd0cf7bc5d80e6"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.0.10+0/Libtiff.v4.0.10.i686-linux-gnu.tar.gz"
