[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "1c109cc49300a0f1196efac571a07a53b1af1bc1"
os = "macos"

    [[Libtiff.download]]
    sha256 = "14056a2499c50ce04e093b861d30a50494d081916ac6658e4954ae27054d29c7"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.aarch64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "172e841c16e1f94d3f852f0d5416e02b82b3b83c"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "316d61c790bd256b598489b28e79a36ba3e848897517f7305b2114cc5125d335"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "2f8d2e0a5acaec6c6ce5f29366828cb8779a1dbd"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "b971fbbdafedf3331fc30b4cb6240741b0a6e7dfc87c4fdee72dfb6425c3f8c3"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c41d1fa748478339028d57ffbf635a09bad62ad7"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "bf0a02730ae1c7193ee9ffc0b40a7190b49b9b268e1d57bf1816a90c18672aab"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.armv6l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e50e2a483dfe02563db1cdb14a55434945343c87"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "b423e62298d3e602951eeb9661417915c5e43185b66defd63d2764710bb11031"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.armv6l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5030c54ff8dd10e3dd8703ee6915a703bc2a35ce"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "c0d8f75913e25db5f41deb7ccff6147959f3e28b6727d33eff128585a0bc4908"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.armv7l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e4d29f25a82071526a16d91fa43233cf9788893b"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "477ab9c925dbaf48b5e7fde337c3f4cd8f362f03db2d1b61818208e85d5e2848"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.armv7l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "ffdb8755195d4ee63707753643c6dd67b25cd42c"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "0013212a3f5dc8b20728ad0acb87d6ed9227961c056d6f8b2206843b34ee46c3"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.i686-linux-gnu.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "f630af06ef0fd5328f045f4800e30dd5aa7038ba"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "c6907ace5361cbf93adc266baf5e5f8019af54bcea7cc09ed7864eaf3a025b3e"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "80987febd34ae6a76718378a114a4ea960825a72"
os = "windows"

    [[Libtiff.download]]
    sha256 = "e296a73c1b2fb64c51841feae602d4a5971cdc1c7da1828e933ebc02526e237b"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "64e14698b25b48f29a81c1f13b564410a60025b5"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d17b6e4c3e73606c8118f3dee9411cc542578db3121d19b2936253fd40fbdb01"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "201a63c30cb17a6cfac205ccc7ec3c1e34b7e98f"
os = "macos"

    [[Libtiff.download]]
    sha256 = "29d87300b0e3ba196e18ce6ebfc1f37002388c340918d99771a04fb6c111cac2"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.x86_64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "6101eed2e2d457a5d9d1ff7b9262cf3a967f4085"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "4ba880de239fa607f03c80999c2c2b6394a9d8f9f76c73faeeb13b6a5397c664"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "0226d23d31f5d440f5a85132c3cf15d770f6077a"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d672b417f3b5fd2d97814ba019c9d467cb1b5c646480b192fa4e0b2067897949"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.x86_64-linux-musl.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "8a65c6d7f8cbffc26bd12b33b28be585c203db1d"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "f04b58969cb2d734fc77c0255acaa7163d78d0e9ca9df81ee6c89b10de3e30fc"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.x86_64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "c95e28424cbf7c6e1fa2379500eedc6c260b3676"
os = "windows"

    [[Libtiff.download]]
    sha256 = "12e2295eec4807492aea6073e4b0cd02e554910fddfe38d4eb7711b9a4a0d510"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.5.1+0/Libtiff.v4.5.1.x86_64-w64-mingw32.tar.gz"
