[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "90aba84be27431afda9bb9fe1335b46353fe04a0"
os = "macos"

    [[Libtiff.download]]
    sha256 = "61c7fe4cf574e95dc5a67a65cad69fa6b0b97d2726d51d6cdf8cb168854704ee"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.aarch64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "ea061bdc58c073fcb3c0683469061c29087803b1"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "7f7aa33cd34eb3c02d4cc46579b7c80242f9944dd458536a41a3ee308af6714f"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.aarch64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "c5c1d8b1107ba85803db0b542de732739bdd08e1"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "a2bccdeafb9e72ed0febf785cd460a999cc25b711fc9b9768de211d3ab71e752"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.aarch64-linux-musl.tar.gz"
[[Libtiff]]
arch = "aarch64"
git-tree-sha1 = "44746417cb10b3fc7417cc4e7a0d0b5a1f00c62e"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "e3f4fe8f994e72a9ae5bad1fd104c9bf0dfe3ab385d8843876816c5e5688b4a4"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.aarch64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5907f185ffb9ab8878e3080b94314addb68e41f0"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "267405db16db013beb7e204995addaceda2789b4e84db748d56d85e42139a91e"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.armv6l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5883c73c468c8353a8f971e0373e59922e341433"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "aee25a9d5b04d7ea9cdbf2938e6d5eaddc5ab2cf8dc85c21f7d07273de97d9de"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.armv6l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2d5edee96283a4827ec67bb624e6e0998ab2004"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "f6a540a2a20f53947da42cf06f6bafc199e75cf96c2559c8cd7dc86e25614d79"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.armv7l-linux-gnueabihf.tar.gz"
[[Libtiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eab2d8a23ad5f56fbf555c961518baae4bfb23b1"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "4ada54424e8224d72c8aea66e3909152272b2b7a7f8f42c4173fe331f1b18cfb"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.armv7l-linux-musleabihf.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "22e9e5a1b02cf99bab35eac8eb6dbc0e59283ded"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "6b2bff2252ad87cffca0ebea8e83d000af59c460fd5b7a228e1bff2e7dfcd8ad"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.i686-linux-gnu.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "a43ac2420c08f44f9b1fe85568c5a9b67231c761"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "e854ec1a16022ea9241b5e04b20aafdff9374571fc8278a71aeda9088bdf05b9"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.i686-linux-musl.tar.gz"
[[Libtiff]]
arch = "i686"
git-tree-sha1 = "53411fd2b6db5563552cf6c02e1ab9dd4b99315c"
os = "windows"

    [[Libtiff.download]]
    sha256 = "65a0cc2b3a23be95c622f2f782dda48459125db5de0c0998a3ae1819cc1f3b99"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.i686-w64-mingw32.tar.gz"
[[Libtiff]]
arch = "powerpc64le"
git-tree-sha1 = "74d28f412f859133f01c2174b15738eb5e65bb85"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "0986ca2f87826ac362bda1194bcc48823445636255e476f166baa878934af83f"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.powerpc64le-linux-gnu.tar.gz"
[[Libtiff]]
arch = "riscv64"
git-tree-sha1 = "632872b31981703c856bf2e34f01ce064a296365"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "d03b365200d46cf502bd64039a2df4600cf09358e24421ba35dfc437f5d96042"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.riscv64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "b838e60e0c06c6780d59380fc0373460c47fa6d7"
os = "macos"

    [[Libtiff.download]]
    sha256 = "0ec418c3d0cefba22a6a6c3659d12a2bdc3e174df592036697ca80016aefd2be"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.x86_64-apple-darwin.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "f746a7e21d913266a25123e53be3ba958917c96a"
libc = "glibc"
os = "linux"

    [[Libtiff.download]]
    sha256 = "ab78f6094dd9024bc3c0c492742d4b7b13f1b4829e7b7352031bcb08126493a3"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.x86_64-linux-gnu.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "e270a5a18739805febf90b8e81157325d619dea8"
libc = "musl"
os = "linux"

    [[Libtiff.download]]
    sha256 = "b3e1c938530aa42761d1dd87b2f67a08a1fe20514f1f0db8c16155c41d6922be"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.x86_64-linux-musl.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "9c4070dd4cb6bb7a136e81190952069e664afc82"
os = "freebsd"

    [[Libtiff.download]]
    sha256 = "b4265a6c73858c29d2811a44ff5976e2aec93efa5252e960db6f38f9d68c7483"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.x86_64-unknown-freebsd.tar.gz"
[[Libtiff]]
arch = "x86_64"
git-tree-sha1 = "bceb83cbb02f69a09fbeb440ce60389ee6ee1afe"
os = "windows"

    [[Libtiff.download]]
    sha256 = "531295ee4c0a3d752d431fad4d61e37789f8f27552c4581d798dcd5e8d52a2b5"
    url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.7.2+0/Libtiff.v4.7.2.x86_64-w64-mingw32.tar.gz"
